import Head from 'next/head'
import { Box, Center, Stack, Text } from "@chakra-ui/react";
import { BingoSheet } from "components/bingo/sheet";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center py={8}>
        <Stack>
          <Box py={4}>
            <Text fontSize={24}>Let's play Bingo!!</Text>
          </Box>
          <Box>
            <BingoSheet />
          </Box>
        </Stack>
      </Center>
    </Box>
  )
}
